author: {email: discomap@eea.europa.eu, name: EEA}
description: Access to Eurostat statistics data
fpkg_version: 1
minimum_fme_build: 22623
name: Eurostat
package_content:
  formats:
  - {name: eurostat}
  python_packages:
  - {name: fme-eurostat}
  web_filesystems:
  - {name: Eurostat}
  web_services:
  - {name: Eurostat_v1.xml}
publisher_uid: eea
uid: eurostat
version: 1.0.2
