fpkg_version: 1
uid: eurostat
publisher_uid: eea
name: Eurostat
description: Eurostat TODO
version: 0.0.1
minimum_fme_build: 21222
author:
  name: EEA
  email: discomap@eea.europa.eu
package_content:
  formats:
      - name: eurostat
      - name: eurostatpy
  python_packages:
    - name: fme-eurostat
  web_filesystems:
    - name: Eurostat
  web_services:
    - name: Eurostat_v1.xml
