title: Eurostat FME Package
description: Eurostat FME Package
author: EEA

theme: minima

base_url: /eea.eurostat.api.fme

# Archive from <Today> didnt render
future: true
# Minima social links
# twitter_username: xyz
# github_username: xyz
# linkedin_username: xyz
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/documentation.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - Gemfile
